### ISSUE TITLE
No module named 'nppig_cpp'

### ISSUE THREAD

**Issue by TwinkleYR** [andr345/frtm-vos#11]
Hi, when i run the code, ImportError: No module named 'nppig_cpp'
```
Compiling npp extension
Traceback (most recent call last):
  File "evaluate.py", line 18, in <module>
    from lib.datasets import DAVISDataset, YouTubeVOSDataset
  File "/home/rtm/zc/frtm-vos/lib/datasets.py", line 6, in <module>
    from lib.image import imread
  File "/home/rtm/zc/frtm-vos/lib/image.py", line 6, in <module>
    from ._npp import nppig_cpp
  File "/home/rtm/zc/frtm-vos/lib/_npp/__init__.py", line 16, in <module>
    with_cuda=True, build_directory=_build_dir)
  File "/home/rtm/Envs/py36env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/rtm/Envs/py36env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/rtm/Envs/py36env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/rtm/Envs/py36env/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'nppig_cpp'
```
my environment:
torch1.1.0
py3.6
Do you have any suggestions?

**Comment by BWYWTB** [comment]
Hello bro, Did you solve the problem? Did you compile the nppig.cpp successfully？
