### ISSUE TITLE
resnet18 training

### ISSUE THREAD

**Issue by guillaumejs2403** [andr345/frtm-vos#13]
Hi,

I was trying to train your model with a rs18 as backbone: nonetheless I got the following error:

```
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    trainer.train()
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/lib/training.py", line 130, in train
    stats = self.model(*batch)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/training_model.py", line 95, in forward
    cache_hits = self._initialize(images[0], labels[0], specs)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/training_model.py", line 137, in _initialize
    self.tmodels[i].initialize(ft, lb)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/training_model.py", line 20, in initialize
    self.discriminator.init(ft[self.discriminator.layer], mask)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/discriminator.py", line 175, in init
    optimizer.run(self.init_iters)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/optimizer.py", line 70, in run
    self.run_GN_iter(cg_iter)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/optimizer.py", line 81, in run_GN_iter
    self.f0 = self.problem(self.x)
  File "/media/user_home1/gjeanneret/SOFTWARE/frtm-vos/model/discriminator.py", line 47, in __call__
    s = self.net(self.x)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/home/gjeanneret/anaconda3/envs/frtm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 349, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 1024, 1, 1], expected input[15, 256, 30, 54] to have 1024 channels, but got 256 channels instead
```

I fixed it with ease just by adding an if condition on line
https://github.com/andr345/frtm-vos/blob/64fe1057a7227180036505d54b6e793a9a5d5323/train.py#L59
by adding:
`layer="layer4", in_channels=256 if '18' in feature_extractor else 1024, c_channels=32, out_channels=1`

**Comment by andr345** [comment]
Thanks! Merging it now.
