### ISSUE TITLE
How to solve the problem of 'Permission denied: '/outputs'' in evaluate.py?

### ISSUE THREAD

**Issue by Starboy-at-earth** [andr345/frtm-vos#20]
code ///////////////////////////////////
paths = dict(
        models=Path(__file__).parent / "checkpoints/try",  # The .pth files should be here
        davis="~/disk/MATNet/data/DAVIS2017",  # DAVIS dataset root
        yt2018="/path/to/ytvos2018",  # YouTubeVOS 2018 root
        output="/outputs",  # Output path
    )
traceback////////////////////////////
Traceback (most recent call last):
  File "/home/fg/disk/frtm-vos/evaluate.py", line 152, in <module>
    os.makedirs(out_path)
  File "/home/fg/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/fg/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/outputs'

**Comment by Starboy-at-earth** [comment]
Carefully fulling in the paths variable is the solution.
